name: AdhocExecution
on:
  repository_dispatch:
    types: [test]
  workflow_dispatch:
    inputs:
      tag:
        description: Which set of tests to run
        default: suite_employee_benefits
      environment:
        description: Which environment to run tests against
        default: test
jobs:
  run_tests:
    name: Run
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      # Conditionally set based on which event triggered the run
      TEST_ENVIRONMENT: ${{ (github.event_name == 'repository_dispatch' && github.event.client_payload.environment) || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment) || 'test' }}
      CUCUMBER_TAG: ${{ (github.event_name == 'repository_dispatch' && github.event.client_payload.tag) || (github.event_name == 'workflow_dispatch' && github.event.inputs.tag) || 'suite_employee_benefits' }}
      CUCUMBER_THREAD: 1
      CUCUMBER_JOB_STATUS: 'PASS'
      CUCUMBER_JOB_STATUS_SIGN: ':white_check_mark:'
    steps:
      - name: envdetails
        run: |
          echo ${{ env.CUCUMBER_TAG }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ITPS_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ITPS_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Run Tests
        id: run
        continue-on-error: true
        run: ./gradlew build cucumber -PcucumberTag="@${{ env.CUCUMBER_TAG }}" -PcucumberThreads=${{ env.CUCUMBER_THREAD }}
      - name: Report
        uses: deblockt/cucumber-report-annotations-action@v1.7
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: build/cucumber/bbt_firstRun.json
          name: Run Report
          check-status-on-error: failure
          check-status-on-undefined: neutral
          check-status-on-pending: neutral
      - name: Rerun Tests
        id: rerun
        continue-on-error: true
        run: ./gradlew cucumberRerun -PcucumberTag="@${{ env.CUCUMBER_TAG }}" -PcucumberThreads=${{ env.CUCUMBER_THREAD }}
      - name: Rerun Report
        uses: deblockt/cucumber-report-annotations-action@v1.7
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: build/cucumber/bbt_reRun.json
          name: Rerun Report
          check-status-on-error: failure
          check-status-on-undefined: neutral
          check-status-on-pending: neutral
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: cucumber-reports
          path: "build/cucumber/"
      - name: Fail if we failed
        if: steps.rerun.outcome == 'failure'
        run: exit 1