# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: displaytagname
      run: |
        echo "tagname1=run_test_one" >> $GITHUB_ENV
        echo "tagname2=run_test_two" >> $GITHUB_ENV
        echo "tagname=run_test_three" >> $GITHUB_ENV
        echo ${{ (env.tagname1 == env.tagname2 && env.tagname1) || (env.tagname2 == 'test2' && 'test2') || env.tagname }}
        echo ${{ env.tagname }}        
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: CucumberTest
      continue-on-error: true
     # run: gradle build

    # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
    # the publishing section of your build.gradle
   # - name: Publish to GitHub Packages
      run:  ./gradlew cucumberCli
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: deblockt/cucumber-report-annotations-action@v1.7
      continue-on-error: true
      name: CucumberReport
      with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "**/cucumber-report.json"

    - name: ReRunTest
      continue-on-error: true
      run:  ./gradlew cucumberReRun
      env:
       USERNAME: ${{ github.actor }}
       TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: myghpages
